---
### generate ceph.monmap, ceph.mon.keyring, 
#   ceph.client.admin.keyring, and ceph.bootstrap-osd.keyring 

# these are one-offs unique to each cluster

### example manual generation process
# docker run -d --rm --net=host \
#     --name ceph_mon \
#     -v `pwd`/etc:/etc/ceph \
#     -v `pwd`/var:/var/lib/ceph \
#     -e NETWORK_AUTO_DETECT=4 \
#     -e DEBUG=verbose \
#     ceph/daemon mon
# docker exec -it ceph_mon ceph mon getmap -o /etc/ceph/ceph.monmap
# docker stop ceph_mon

- name: handle no specified destination...
  block:
    - name: create tempdir destination for secrets if dir not provided
      tempfile:
        state: directory
        prefix: "ceph-secrets."
      register: ceph_secrets_tempdir

    - name: set secrets destination to tempdir path
      set_fact: 
        ceph_secrets_dest: "{{ ceph_secrets_tempdir.path }}"
  when:
    - ceph_secrets_dest is None

- name: preset temp container name
  set_fact:
    ceph_secrets_container: "ceph_secrets_{{ ansible_date_time.epoch }}"

- name: start temp container for secret creation
  docker_container:
    name: "{{ ceph_secrets_container }}"
    image: "{{ ceph_image }}"
    volumes:
      - "{{ ceph_secrets_dest }}/etc:/etc/ceph"
      - "{{ ceph_secrets_dest }}/var:/var/lib/ceph"
    network: host
    env:
      - "NETWORK_AUTO_DETECT=4"
      - "DEBUG=verbose"
    command: mon
    state: started

- name: run mon getmap against secrets container
  shell: "docker exec -it {{ ceph_secrets_container }} ceph mon getmap -o /etc/ceph/ceph.monmap"

- name: run mon getmap against secrets container
  shell: "docker exec -it {{ ceph_secrets_container }} ceph osd create"  

- name: verify the appropriate files were created
  block:
    - name: "checking location: {{ item }}"
      stat:
        path: "{{ item }}"
      register: stat_result
    
    - name: "fail if {{ item }} doesn't exist"
      assert: { that: stat_result.exists }
      
  with_items:
    - "/etc/ceph.monmap"
    - "/var/bootstrap-osd/ceph.keyring"
    - "/etc/ceph.client.admin.keyring"
    # - "/etc/ceph.mon.keyring" # this is normally kept in /tmp. if tests pass with this comment, delete the line.

- name: stop and remove the temp container
  docker_container:
    name: "{{ ceph_secrets_container }}"
    state: absent
